
package edu.epam.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICalculatorService", targetNamespace = "http://webservices.epam.edu/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ICalculatorService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.epam.edu/ICalculatorService/calculationRequest", output = "http://webservices.epam.edu/ICalculatorService/calculationResponse")
    public double calculation(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

}
